name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  publish:
    name: "publish"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt \
                      -r requirements/requirements-test.txt \
                      -r requirements/requirements-examples.txt \
                      -r examples/*/requirements.txt

      - name: Run pytype
        run: |
          pytype rax/ examples/

      - name: Run tests
        run: |
          python -m unittest discover -v -s ./rax -p "*_test.py"
          python -m unittest discover -v -s ./examples -p "*_test.py"

      - name: Create package
        run: |
          pip install --upgrade setuptools build twine virtualenv
          python -m build

      - name: Upload package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*

